---
name: bosh-haraka

variables:
- name: haraka_smtp_forward_auth_user
  type: password
- name: haraka_smtp_forward_auth_pass
  type: password

releases:
- name: bosh-haraka
  version: latest 

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: mta
  azs:
  - z1
  instances: 1
  jobs:
  - name: haraka
    release: bosh-haraka
    properties:
        haraka:
            smtp_forward:
                auth_user: ((haraka_smtp_forward_auth_user))
                auth_pass: ((haraka_smtp_forward_auth_pass))
  vm_type: f1-micro
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.0.0.11
