---
name: bosh-haraka

variables:
- name: smtp_username
  type: password
- name: smtp_password
  type: password

releases:
- name: bosh-haraka
  version: latest 

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: mta
  azs:
  - z1
  instances: 1
  jobs:
  - name: haraka
    release: bosh-haraka
    properties:
        haraka:
            smtp_username: ((smtp_username))
            smtp_password: ((smtp_password))
  vm_type: f1-micro
  stemcell: default
  networks:
  - name: default
    static_ips:
    - 10.0.0.11
